version: '3.9'
services:
  web:
    build: .
    command: python -u main.py
    ports:
    - "80:5004"
    image: good777lord/flaskapp1
    restart: always
    networks:
    - webnet

networks:
  webnet:      