apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flaskapp.fullname" . }}
  labels:
    {{- include "flaskapp.labels" . | nindent 4 }}
spec:
 
  replicas: {{ .Values.replicaCount }}
 
  selector:
    matchLabels:
      {{- include "flaskapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flaskapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetport}}
              protocol: TCP
          