apiVersion: v1
kind: Service
metadata:
  name: flaskapp1-service
spec:
  selector:
    app: flaskapp1
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5004
    nodePort: 31121

